---
title: "Reason to use FTM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reason to use FTM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Overview of FTM

Often, with 'omics data, we have a model that we have trained on one dataset and we want to apply it to another dataset. However, the predictors in the new dataset may not be entirely the same as the predictors in the original dataset. This causes an issue, which can traditionally be solved through 2 options:
* Ignore the missing predictors (effectively setting them to 0)
* Recreate the model using a subset of variables that are present in both datasets
FTM overcomes this challenge by allowing the model to be evaluated in datasets without exact overlap in the predictor variables, without loss in generalizability, re-optimization, or access to individual-level data. This is achieved by storing intermediate matrices that allow beta coefficients to be recalculated using a subset of original predictors.

